; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

; Shared settings for all environments
[env]
platform = espressif32
framework = arduino
lib_deps =
	bblanchon/ArduinoJson@^7.2.2
	lsatan/SmartRC-CC1101-Driver-Lib@^2.5.7
	knolleary/PubSubClient@^2.8
	esp32async/ESPAsyncWebServer@^3.10.3
	esp32async/AsyncTCP@^3.4.10
extra_scripts = pre:minify.py
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
build_flags =
	-DCONFIG_ESP_COREDUMP_ENABLE_TO_FLASH=1
	-DCONFIG_ESP_COREDUMP_DATA_FORMAT_ELF=1
	-DCONFIG_ESP_COREDUMP_CHECKSUM_CRC32=1
	-DCONFIG_ESP_TASK_WDT_PANIC=1
	-DCONFIG_ESP_COREDUMP_DECODE_INFO=1
monitor_speed = 115200
monitor_filters =
	time
	esp32_exception_decoder
	log2file

[env:esp32dev]
board = esp32dev

[env:esp32devdbg]
board = esp32dev
build_type = debug


