; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
	links2004/WebSockets@^2.7.3
	lsatan/SmartRC-CC1101-Driver-Lib@^2.5.7
	knolleary/PubSubClient@^2.8
extra_scripts = pre:minify.py
board_build.partitions = min_spiffs.csv
board_build.filesystem = littlefs

[env:esp32devdbg]
build_type = debug
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
	links2004/WebSockets@^2.7.3
	lsatan/SmartRC-CC1101-Driver-Lib@^2.5.7
	knolleary/PubSubClient@^2.8
extra_scripts = pre:minify.py
board_build.partitions = min_spiffs.csv
board_build.filesystem = littlefs